### PR TITLE
Enhancement: Find/Search packets

### PR DESCRIPTION
**Pull request by valdeza**

### CODE REVIEW

**Comment by exectails** [comment]
The form impressed me, well designed, and with hotkeys, very good. Two things I think should be improved.

The Find form is set to open *somewhere*, especially in a multi-monitor environment it's a little irritating if the window opens somewhere on the third monitor, while you have the application open on the first one. I think this should be changed to center on parent, or the position could be saved, so it appears where the user wants it, like the analyzer plugin or Pale itself.

The other thing is that the search is not very intuitive. I tried to find a simple Notice packet by op and was perplexed why it just skipped it when I was clearly able to see it myself. I tried op name, op id, op id with padded zeros... and while I was testing different combinations of settings and inputs I had a hard time identifying the problem: I typed the op name in lower-case, but the search was case-sensitive. Since we're looking for strings here and people are unlikely to want to search case-sensitive, the default should definitely be case-insensitive. *Maybe* with an option to make it sensitive.

On top of those suggestions, there appears to be a conflict right now, so I can't just merge the PR.

**Comment by valdeza** [comment]
While all's taken care of, how would you suggest displaying the "Ops" search option?
What I was thinking is that if the user wanted to search for the op name they would choose the String search mode, and if they wanted to search for the op code they would choose the Hexadecimal search mode.
It could just be me, but having two op checkboxes just seems.. weird.

(Also, it turns out the conflict was just more Visual Studio shenanigans)

**Comment by exectails** [comment]
Personally I think the search should be as straight forward and easy to use as possible. It is very, *very* unlikely that you'll find an op name and an op code that are identical, so as a user I would expect the search to search for both. The string/hex setting makes sense for the programmer that added it, but not for the average user, who we expect to use this application to supply us with information.

**Comment by valdeza** [comment]
Yeah, you're right. Definitely was just me since I made the thing.

Anyway, hope these few bits helps you guys. Can barely find the time to do much and yet you seem to have an astonishing commit streak going on.

**Comment by exectails** [comment]
Thanks =)

**Pull request merged**
