### PR TITLE
Support for MultiHit TargetOption

### PR DESCRIPTION
**Pull request by xeroplz**
Added support for packs with MultiHit. Previously, they would cause an exception.

### CODE REVIEW

**Comment by xeroplz** [comment]
it is o-o it's only there if MultiHit option is there. If MultiHit is an option, then an Int will be placed instead of a byte, which was the problem.

**Comment by exectails** [comment]
@xeroplz That's probably what @QewQew meant, you should check for the option, not for the type. If the option is set, they're there, because these information are required for that option. But what if another option adds completely different stuff at that location?

**Comment by exectails** [comment]
I've just tried this fix on a Bullet Storm action with one target, in that case you only have 3 instead of 4 ints. We need more research on this.

**Comment by exectails** [comment]
I'll close this for now, since it's outdated and never received the research it needed. Feel free to open it again though.

**Pull request closed without merging**
